language: cpp

compiler:
    - gcc 

before_install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update -qq
    - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"l fi

before_script:
    - mkdir build
    - cd build
    - cmake ..

script: make
