language: cpp

compiler:
    - gcc 

before_install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq gcc-4.9 g++-4.9
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9
    - export CXX="g++-4.9" CC="gcc-4.9"

before_script:
    - mkdir build
    - cd build
    - cmake ..

script: make
